apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: upload-service
  name: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: upload-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: upload-service
    spec:
      containers:
        - image: upload-service
          name: upload-service-container
          ports:
            - containerPort: 5001
          resources: {}
      restartPolicy: Always
status: {}
